name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # corre todos os dias à 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write          # necessário para fazer push na branch output

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: 7Rios
          outputs: |
            dist/snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
